Modified reputation logic docs
EvernodeXRPL/evernode-docs pull request #54
Opened 2024-09-27 06:41 UTC by chalith

2024-09-27 06:48 UTC, du1ana requested changes

2024-09-27 06:48 UTC, du1ana commented on docs/source/hosts/evernode-host-reputationd.md
> +Note: If you have maintained a good reputation, Your rewards won't be affected if you have been assigned to a dud universe because your `score` won't get updated when you are in a dud universe and th
add a comma after "for two moments"

2024-09-27 07:00 UTC, BimsaraFernando commented on docs/source/hosts/evernode-host-reputationd.md
> +    - **Case 5:** If the host hasn't been in a universe for recent two moments. Which means the reputation isn't reset withing last two moments (The `lastResetMoment` isn't withing last two moments).
change the working to "within the last two moments"

2024-09-27 10:02 UTC, BimsaraFernando approved these changes

2024-09-30 04:15 UTC, kithminisg approved these changes

2024-09-30 04:16 UTC, merged